### ISSUE TITLE
Kitchen Button Glitch

### ISSUE THREAD

**Issue by Khenderson11** [luceroweb/haunted-house-game#86] opened 2021-10-27 18:00 UTC
Webpage glitch.

**Comment by Khenderson11** [comment] 2021-10-27 18:02
## Devices
Device name	DESKTOP-4C8P8US
Processor	AMD FX(tm)-6300 Six-Core Processor                3.50 GHz
System type	64-bit operating system, x64-based processor
Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

## Expected Behavior
When user clicks on "Kitchen" the user is taken to the kitchen page.

## Actual Behavior
When user click on "Kitchen" the screen glitches and does not take the user to the Kitchen page or any other page.

## Steps to Reproduce Issue
"1. Go to https://luceroweb.github.io/haunted-house-game/#/
2. Click ""Skip to Gameplay""
3. Click ""Kitchen"""

## Screenshots

## Notes
Not always able to recreate bug

**Comment by SmiJa** [comment] 2021-10-27 19:52
@Khenderson11 @lreyes-qae 
We weren't able to reproduce this one. We have found that the link works when clicking in the margin around the buttons, and were curious if that may be a part of the issue.

**Comment by lreyes-qae** [comment] 2021-10-28 20:45
@SmiJa  and @luceroweb I have been testing this on both mobile and desktop using Chrome browser and I too cannot reproduce this issue. I am making the call in that we are OK to close this issue as "Cannot Reproduce." If we do see this happen again in the future, we can always reopen this ticket or create a new ticket. Thank you.

**Closed as completed** 2021-10-28 23:44 UTC
Labels: cannot reproduce
